name: Docker Image CI

on:
  push:
    branches: [ "master" ]

env:
  REPO_NAME : ${{ secrets.DOCKER_USERNAME }}/tagger


jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Current time
      run: echo "TIME=$(date +'%Y_%m_%d_%H_%M_%S')" >> $GITHUB_ENV

    - name: Echo current time
      run: echo $TIME



    - name : Checkout
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{env.REPO_NAME}}:latest , ${{env.REPO_NAME}}:dev_${{env.TIME}}
